apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
spec:
  replicas: 1
  serviceName: mongo-db
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: sethshines/mongo-db:0.1
        ports:
        - containerPort: 27017
          name: mongo-db
        volumeMounts:
        - name: mongo-db-persistent-storage-5
          mountPath: /var/lib/mongo-db
  volumeClaimTemplates:
  - metadata:
      name: mongo-db-persistent-storage-5
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi