# Deployment of MongoDB Container
# Exposes 27017
# Uses Persistent Volume
# Single POD
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
spec:
  replicas: 1
  serviceName: mongo-db
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: sethshines/nagp-mongo-db:1.0
        ports:
        - containerPort: 27017
          name: mongo-db
        volumeMounts:
        - name: mongo-db-persistent-storage-5
          mountPath: /var/lib/mongo-db
        env:
          - name: db_collection
            valueFrom:
              secretKeyRef:
                name: db-config
                key: db_collection
          - name: db_user
            valueFrom:
              secretKeyRef:
                name: db-config
                key: db_user
          - name: db_pass
            valueFrom:
              secretKeyRef:
                name: db-config
                key: db_pass
          - name: db_name
            valueFrom:
              secretKeyRef:
                name: db-config
                key: db_name
  volumeClaimTemplates:
  - metadata:
      name: mongo-db-persistent-storage-5
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi