apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
spec:
  replicas: 1
  serviceName: db-service
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: sethshines/nagp-mongo-db:1.0
        ports:
        - containerPort: 27017
          name: mongo-db
        env:
        - name: db_collection
          valueFrom:
            secretKeyRef:
              name: db-config
              key: db_collection
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: db-config
              key: db_user
        - name: db_pass
          valueFrom:
            secretKeyRef:
              name: db-config
              key: db_pass
        - name: db_name
          valueFrom:
            secretKeyRef:
              name: db-config
              key: db_name
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-storage
  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
